#!/usr/bin/env python3
"""Render the MiSTer credits-overlay bitmap (src/mister/rtl/credits_pages.hex).

The MiSTer About/Credits submenu pages (CONF_STR "Pn-,text;" lines) do not
render on all framework builds, so the core draws its own overlay instead:
escape_credits.v streams this 1bpp bitmap - two 336x240 pages - over the video
output while the mappable Credits button cycles page 1 -> page 2 -> off.

The text below is the SAME attribution set docs/MISTER.md carries in full;
edit here, re-run, commit the regenerated hex alongside. PIL's built-in
bitmap font is used, so the output is deterministic for a given Pillow
version and carries no third-party font asset.

Usage: python3 support/gen_credits_overlay.py
"""
import os
from PIL import Image, ImageDraw, ImageFont

W, H = 336, 240
PAGES = [
    [
        "ATARI DUAL 68K - EPROM",
        "MISTER BUILD 142",          # BUMP with every MiSTer build: this line
                                      # doubles as the boot-splash stamp, the
                                      # only on-device proof of which rbf runs
        "@spoonelli_dev",
        "",
        "Escape from the Planet",
        "of the Robot Monsters",
        "Atari Games 1989",
        "",
        "Core license: GPL-3.0",
        "Requires your own MAME",
        "'eprom' romset - no ROM",
        "data is included.",
        "",
        "Thanks:",
        "LMSS DJS LCS TBPL EG",
        "",
        "        - page 1 of 2 -",
    ],
    [
        "RTL base (GPL-3.0):",
        "MiSTer-devel Arcade-",
        "Atari-system1 by d18c7db",
        "(Alex), incl. TMS5220",
        "",
        "68000s: TG68K.C, Tobias",
        "Gubener (TobiFlex),",
        "LGPL-3.0; patches MikeJ,",
        "Till Harbaum, Rok Krajnc",
        "",
        "JSA 6502: T65, D.Wallner",
        "YM2151: jt51 by jotego",
        "(GPL-3.0)",
        "",
        "Reference only: MAME,",
        "eprom.cpp (Aaron Giles,",
        "BSD-3-Clause). No MAME",
        "source copied.",
        "",
        "        - page 2 of 2 -",
    ],
]

font = ImageFont.load_default()
out = []
for lines in PAGES:
    im = Image.new('1', (W, H), 0)
    d = ImageDraw.Draw(im)
    y = 6
    for ln in lines:
        d.text((12, y), ln, fill=1, font=font)
        y += 11
    out.append(im)

dst = os.path.join(os.path.dirname(__file__), '..', 'src', 'mister', 'rtl',
                   'credits_pages.hex')
with open(dst, 'w') as f:
    f.write("// generated by support/gen_credits_overlay.py - do not edit\n")
    for im in out:
        px = im.load()
        for y in range(H):
            for xb in range(W // 8):
                b = 0
                for k in range(8):
                    if px[xb * 8 + k, y]:
                        b |= 0x80 >> k
                f.write("%02x\n" % b)
print("wrote", dst, "(%d bytes)" % (len(out) * H * (W // 8)))
