import re, sys
src = open(sys.argv[1]).read()
m = re.search(r'\bentity\s+escape_core\s+is(.*?)\bend\s+(entity|escape_core)', src, re.S|re.I)
body = re.sub(r'--[^\n]*', '', m.group(1))
pm = re.search(r'\bport\s*\((.*)\)\s*;\s*$', body.strip(), re.S|re.I)
out=[]; depth=0; cur=''
for ch in pm.group(1):
    if ch=='(': depth+=1
    if ch==')': depth-=1
    if ch==';' and depth==0: out.append(cur); cur=''
    else: cur+=ch
out.append(cur)
decls=[]
for p in out:
    p=p.strip()
    if not p: continue
    name_part, type_part = p.split(':',1)
    names=[n.strip() for n in name_part.split(',')]
    t=type_part.strip()
    dm=re.match(r'(in|out|inout)\s+(.*)', t, re.I)
    direction=dm.group(1).lower(); rest=dm.group(2).split(':=')[0].strip()
    vm=re.search(r'std_logic_vector\s*\(\s*(\d+)\s+downto\s+(\d+)\s*\)', rest, re.I)
    hi = int(vm.group(1)) if vm else None
    kw={'in':'input','out':'output','inout':'inout'}[direction]
    for n in names: decls.append((kw,hi,n))
# ports whose behaviour the bench supplies by hand
HAND = {'pf_vdata','pfx_vdata'}
L=[]
L.append("// AUTO-GENERATED by support/mk_core_stub.py from src/fpga/core/rtl/escape_core.vhd.")
L.append("// SIMULATION STUB ONLY - never synthesised, never in files.qip.")
L.append("// It exists so iverilog can elaborate the REAL src/mister/rtl/escape_mister.v")
L.append("// (Verilog) without the VHDL machine.  Everything is tied off except the")
L.append("// playfield tilemap port, which returns a synthetic map so the PF fetch")
L.append("// addresses vary the way they do in a real scene.")
L.append("`default_nettype none")
L.append("module escape_core #(")
L.append("    parameter PAR4_EN=0, parameter FASTPATH_EN=1, parameter EIRQ_MODE=2, parameter TASLOCK_EN=1")
L.append(") (")
L.append(",\n".join(f"    {k} wire {('['+str(h)+':0] ') if h is not None else ''}{n}" for k,h,n in decls))
L.append(");")
for k,h,n in decls:
    if k!='output' or n in HAND: continue
    zero = (str(h+1) + "'d0") if h is not None else "1'b0"
    L.append("assign " + n + " = " + zero + ";")
L.append("""
// Synthetic playfield map: a 64x64 column-major map of varying tile codes,
// enough that every fetch targets a different 32-byte tile row.
assign pf_vdata  = {1'b0, 3'd0, pf_vaddr[11:0]};        // code = map index
assign pfx_vdata = {4'd0, 4'd3, 8'd0};                  // colour attribute = 3
endmodule
`default_nettype wire""")
print("\n".join(L))
