// escape_credits: the core-credits overlay (MiSTer).
//
// WHY THIS EXISTS. The attributions used to live in CONF_STR submenu pages
// ("Pn-,text;" lines). That is pure framework menu text - and on the owner's
// framework build those pages render EMPTY, so the attribution was silently
// unreachable. This module draws the credits in the CORE's own video path
// instead, where no framework version can lose them: a 1bpp two-page bitmap
// (rtl/credits_pages.hex, generated by support/gen_credits_overlay.py -
// regenerate and commit both together) streamed over the game picture. The
// mappable Credits button cycles page 1 -> page 2 -> off.
//
// TIMING. The colour path this overlays is two clocks behind the raster
// counters (escape_mister.v "video output registers" note). This pipeline is
// built to the same depth: address registered from the live counters (stage
// 1), BRAM data registered (stage 2), so ov_px lands on exactly the pixel the
// palette data lands on and needs no external delay matching. The bit select
// uses a two-stage-delayed copy of x[2:0] for the same reason.
//
// COST. 20,160 bytes = 2 M10K on the DE10's 553 (168 were spare at 131).
// Nothing is fetched from game ROM: the bitmap is project-authored text.
`default_nettype none

module escape_credits #(
    parameter [9:0] H_BPORCH = 10'd60,
    parameter [9:0] V_BPORCH = 10'd12,
    parameter [9:0] H_ACTIVE = 10'd336,
    parameter [9:0] V_ACTIVE = 10'd240
) (
    input  wire       clk,
    input  wire [1:0] page,        // 0 = off, 1..2 = page select
    input  wire [9:0] x_count,
    input  wire [9:0] y_count,
    output wire       ov_on,       // overlay active (dim the game video)
    output wire       ov_px        // this pixel is lit text
);
    reg [7:0] mem [0:20159];       // 2 pages x 240 rows x 42 bytes
    initial $readmemh("rtl/credits_pages.hex", mem);

    wire [9:0] vx = x_count - H_BPORCH;
    wire [9:0] vy = y_count - V_BPORCH;
    wire       vis = (x_count >= H_BPORCH) && (x_count < H_BPORCH + H_ACTIVE)
                  && (y_count >= V_BPORCH) && (y_count < V_BPORCH + V_ACTIVE);

    // page*10080 + vy*42 + vx[8:3], all registered (stage 1)
    reg  [14:0] addr_q;
    reg         vis_d1, vis_d2;
    reg  [2:0]  bx_d1, bx_d2;
    reg  [7:0]  data_q;
    always @(posedge clk) begin
        addr_q <= (page == 2'd2 ? 15'd10080 : 15'd0)
                  + {vy[7:0], 5'b0} + {vy[7:0], 3'b0} + {vy[7:0], 1'b0}  // vy*42
                  + {9'b0, vx[8:3]};
        data_q <= mem[addr_q];                                  // stage 2
        vis_d1 <= vis;      vis_d2 <= vis_d1;
        bx_d1  <= vx[2:0];  bx_d2  <= bx_d1;
    end

    assign ov_on = (page != 2'd0);
    assign ov_px = ov_on && vis_d2 && data_q[3'd7 - bx_d2];
endmodule

`default_nettype wire
