// AUTO-GENERATED by support/mk_core_stub.py from src/fpga/core/rtl/escape_core.vhd.
// SIMULATION STUB ONLY - never synthesised, never in files.qip.
// It exists so iverilog can elaborate the REAL src/mister/rtl/escape_mister.v
// (Verilog) without the VHDL machine.  Everything is tied off except the
// playfield tilemap port, which returns a synthetic map so the PF fetch
// addresses vary the way they do in a real scene.
`default_nettype none
module escape_core #(
    parameter PAR4_EN=0, parameter FASTPATH_EN=1, parameter EIRQ_MODE=2, parameter TASLOCK_EN=1
) (
    input wire clk,
    input wire reset_n,
    output wire [23:0] rom_addr,
    input wire [31:0] rom_data,
    input wire rom_par,
    input wire [3:0] rom_par4,
    output wire rom_req,
    input wire rom_ack,
    output wire [23:0] fast_v_addr,
    output wire fast_v_spec,
    input wire [15:0] fast_v_data,
    input wire fast_v_ready,
    output wire [23:0] fast_e_addr,
    output wire fast_e_spec,
    input wire [15:0] fast_e_data,
    input wire fast_e_ready,
    input wire shad_wclk,
    input wire [23:0] shad_waddr,
    input wire [15:0] shad_wdata,
    input wire shad_we,
    input wire [8:0] ee_saddr,
    input wire [7:0] ee_sdin,
    input wire ee_swe,
    output wire [7:0] ee_sq,
    output wire ee_wrpulse,
    input wire vblank_in,
    input wire [3:0] p1_buttons,
    input wire [3:0] p2_buttons,
    input wire [7:0] adc_p1x,
    input wire [7:0] adc_p1y,
    input wire [7:0] adc_p2x,
    input wire [7:0] adc_p2y,
    input wire svc_n,
    input wire coin1,
    input wire coin2,
    input wire step_btn,
    input wire skip_test,
    input wire irq_strict,
    input wire [2:0] uvol_ym,
    input wire [2:0] uvol_tms,
    input wire [23:0] uvol_fm,
    output wire [15:0] audio_l,
    output wire [15:0] audio_r,
    input wire [10:0] alpha_vaddr,
    output wire [15:0] alpha_vdata,
    input wire [10:0] color_vaddr,
    output wire [15:0] color_vdata,
    input wire [11:0] pf_vaddr,
    output wire [15:0] pf_vdata,
    input wire [11:0] pfx_vaddr,
    output wire [15:0] pfx_vdata,
    input wire [11:0] mo_vaddr,
    output wire [15:0] mo_vdata,
    input wire [6:0] cfg_vaddr,
    output wire [15:0] cfg_vdata,
    output wire [8:0] xscroll_out,
    output wire [8:0] yscroll_out,
    output wire [3:0] intensity_out,
    output wire video_off_out,
    input wire dbg_force_extra,
    input wire dbg_shr_we,
    input wire [14:0] dbg_shr_addr,
    input wire [15:0] dbg_shr_din,
    output wire dbg_v_pc_fetch,
    output wire dbg_e_running,
    output wire dbg_alpha_wr,
    output wire [15:0] dbg_mbox_cmd,
    output wire [15:0] dbg_mbox_resp,
    output wire [15:0] dbg_mbox_ramr,
    output wire [15:0] dbg_mbox_sum,
    output wire [15:0] dbg_mbox_cnts,
    output wire mbox_dead,
    output wire [15:0] dbg_pf_wcnt,
    output wire [15:0] dbg_pf_last,
    output wire [15:0] dbg_col_wcnt,
    output wire [15:0] dbg_boot,
    output wire [15:0] dbg_retry,
    output wire [15:0] dbg_engine,
    output wire [15:0] dbg_mode,
    output wire [15:0] dbg_ecrash_pc,
    output wire [15:0] dbg_ecrash_data,
    output wire [7:0] dbg_erestart,
    output wire [15:0] dbg_estall,
    output wire [15:0] dbg_vcyc,
    output wire [15:0] dbg_ecyc,
    output wire [15:0] dbg_ewild,
    output wire dbg_eintab,
    output wire [15:0] dbg_awr,
    output wire [15:0] dbg_tas_cnt,
    output wire [15:0] dbg_tas_addr,
    output wire [15:0] dbg_ewrong,
    output wire [3:0] dbg_ewrong_cnt,
    output wire [15:0] dbg_ewrong_prev,
    input wire [6:0] trace_idx,
    input wire trace_hold,
    output wire [42:0] trace_q,
    output wire [6:0] trace_wp,
    output wire trace_frozen,
    output wire e_dead,
    output wire [15:0] dbg_a84_wr,
    output wire [15:0] dbg_a84_rd,
    output wire [15:0] dbg_pc,
    output wire [15:0] dbg_wrhi,
    output wire [15:0] dbg_vec,
    output wire dbg_fault,
    output wire [15:0] dbg_fdata,
    output wire [1:0] dbg_fsrc,
    output wire [15:0] dbg_epc,
    output wire [15:0] dbg_jsa_link,
    output wire [15:0] dbg_jsa_pc,
    output wire [15:0] dbg_resp_stat,
    output wire [15:0] dbg_coin_cred,
    output wire wdog_expired
);
assign rom_addr = 24'd0;
assign rom_req = 1'b0;
assign fast_v_addr = 24'd0;
assign fast_v_spec = 1'b0;
assign fast_e_addr = 24'd0;
assign fast_e_spec = 1'b0;
assign ee_sq = 8'd0;
assign ee_wrpulse = 1'b0;
assign audio_l = 16'd0;
assign audio_r = 16'd0;
assign alpha_vdata = 16'd0;
assign color_vdata = 16'd0;
assign mo_vdata = 16'd0;
assign cfg_vdata = 16'd0;
assign xscroll_out = 9'd0;
assign yscroll_out = 9'd0;
assign intensity_out = 4'd0;
assign video_off_out = 1'b0;
assign dbg_v_pc_fetch = 1'b0;
assign dbg_e_running = 1'b0;
assign dbg_alpha_wr = 1'b0;
assign dbg_mbox_cmd = 16'd0;
assign dbg_mbox_resp = 16'd0;
assign dbg_mbox_ramr = 16'd0;
assign dbg_mbox_sum = 16'd0;
assign dbg_mbox_cnts = 16'd0;
assign mbox_dead = 1'b0;
assign dbg_pf_wcnt = 16'd0;
assign dbg_pf_last = 16'd0;
assign dbg_col_wcnt = 16'd0;
assign dbg_boot = 16'd0;
assign dbg_retry = 16'd0;
assign dbg_engine = 16'd0;
assign dbg_mode = 16'd0;
assign dbg_ecrash_pc = 16'd0;
assign dbg_ecrash_data = 16'd0;
assign dbg_erestart = 8'd0;
assign dbg_estall = 16'd0;
assign dbg_vcyc = 16'd0;
assign dbg_ecyc = 16'd0;
assign dbg_ewild = 16'd0;
assign dbg_eintab = 1'b0;
assign dbg_awr = 16'd0;
assign dbg_tas_cnt = 16'd0;
assign dbg_tas_addr = 16'd0;
assign dbg_ewrong = 16'd0;
assign dbg_ewrong_cnt = 4'd0;
assign dbg_ewrong_prev = 16'd0;
assign trace_q = 43'd0;
assign trace_wp = 7'd0;
assign trace_frozen = 1'b0;
assign e_dead = 1'b0;
assign dbg_a84_wr = 16'd0;
assign dbg_a84_rd = 16'd0;
assign dbg_pc = 16'd0;
assign dbg_wrhi = 16'd0;
assign dbg_vec = 16'd0;
assign dbg_fault = 1'b0;
assign dbg_fdata = 16'd0;
assign dbg_fsrc = 2'd0;
assign dbg_epc = 16'd0;
assign dbg_jsa_link = 16'd0;
assign dbg_jsa_pc = 16'd0;
assign dbg_resp_stat = 16'd0;
assign dbg_coin_cred = 16'd0;
assign wdog_expired = 1'b0;

// Synthetic playfield map: a 64x64 column-major map of varying tile codes,
// enough that every fetch targets a different 32-byte tile row.
assign pf_vdata  = {1'b0, 3'd0, pf_vaddr[11:0]};        // code = map index
assign pfx_vdata = {4'd0, 4'd3, 8'd0};                  // colour attribute = 3
endmodule
`default_nettype wire
